### ISSUE TITLE
plugin proposal

### ISSUE THREAD

**Issue by Verciak** [Vrekt/ArcNukkit#2]
proposes to add noclip, this is very necessary for faction servers.

**Comment by Vrekt** [comment]
This is planned, I'll have to look into it tomorrow.

Only problem I have with those types of checks is they can be very difficult to get right and could cause performance problems.

**Comment by Vrekt** [comment]
Do you have any other recommendations on what to add?

**Comment by Verciak** [comment]
yes, I would suggest adding a clicks per second limit.  if a player reaches, for example, 12 such clicks in a second, then it should block him from hitting for 5 seconds.  Unfortunately, you can't do it on listening in on the impact sound because then it's suboptimal, I checked it on a server that had 70 people and the server had terrible lag because of it.

**Comment by Verciak** [comment]
In general, if you need any ideas what to add or change, you can give a discord and I will write to you about everything.  I have a server with 600 people and I need a good anticheat.  Therefore, I am happy to help you develop it.

**Comment by Vrekt** [comment]
Didn’t think about the clicks limit. I have better combat checks in my Bukkit anti cheat but with bedrock i’m not as experienced so some things get overlooked and plus it’s not so simple over on bedrock unfortunately 😅.

My discord is vrekt#4387

**Comment by Verciak** [comment]
I did this cps limit myself And unfortunately I had no idea for any other use than listening to the sound of the impact

**Comment by Verciak** [comment]
Im invite you
